### ISSUE TITLE
Waiting for resources to finish loading

### ISSUE THREAD

**Issue by joostverdoorn** [FelixAkk/nota#1]
We have the following use case:

We want an image to be rendered in the DOM, and have to source of that image be dynamic. We can add the url of that image in the JSON, and then have rivets set the `src` of the image. However, Nota doesn't wait for the image to be loaded. 

PhantomJS exposes the `onResourceRequested` and `onResourceReceived` methods, which can be used to keep a counter. See https://gist.github.com/Kukunin/f1d43bfec054dd95cd26 for an example. We could use something like that to make sure Nota doesn't create the pdf before all resources are loaded.

I can add this when you're a bit further in your refactoring effort, as I don't want to create conflicts between our and your version.

**Comment by FelixAkk** [comment]
This shouldn't be a problem. Because it's a backend concern I'd preferably solve this with the PhantomJS methods, but otherwise we could fix that clientside by rounding up all the image DOM elements and catching their events when finishing loading.

**Comment by FelixAkk** [comment]
This is fixed in v1.2.0, where for both static and scripted templates it'll ensure all resources are loaded.
