### ISSUE TITLE
Use grunt to build nota pdfs

### ISSUE THREAD

**Issue by joostverdoorn** [FelixAkk/nota#10]
I think it would be a good idea to add grunt and gulp tasks for generating nota pdfs. As such, templates could live in there own repositories and only add nota via `package.json`. In the `Gruntfile.js` one could then specify the main html, js and `example.json`. One could then generate a pdf using something like `grunt nota data=data.json output=output.pdf`

**Comment by FelixAkk** [comment]
Ooh this would be really cool! :D
